apiVersion: v1
kind: ReplicationController
metadata:
  name: repica1
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: create
      labels:
        app: nginx
    spec:
      containers:
        - name: container
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP    
            