---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-rs
  labels:
    app: jenkins
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: prash-pod
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins
          name: prash-container
          ports:
            - containerPort: 8080
              name: pod
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prasha-service
  labels: 
  app: jenkins
  spec:
    ports:
      - name: prashnth-service
        protocol: TCP
        targetPort: 8080
    selector:
      app: jenkins
    type: LoadBalancer      
